### ISSUE TITLE
[FR] Support 8x32 Matrix?

### ISSUE THREAD

**Issue by BigDi** [amonbenson/WiFi-Matrix#1]
I build an [AWTRIX display](https://www.thingiverse.com/thing:2791276). Internal it is a 8x32 WS2812b matrix. The client part (e.g. ESP8266) is open source but the server part is closed source.
It is also written in JAVA and use permanent CPU usage. The display is working fine but nevertheless I'm looking for somehting similar and your project looks like that.
Are you interessent in support such a display?

**Comment by amonbenson** [comment]
Yes, the code should work for 8x32 aswell. The intention is that the esp drives the matrix, runs the logic and hosts the webserver all at once. Atm I cannot test on the actual matrix, so i can't promise if it works out of the box. When I have something working, I will also write a more detailed tutorial.
