### ISSUE TITLE
esp8266 ws2812b 32x8

### ISSUE THREAD

**Issue by skadzynski** [amonbenson/WiFi-Matrix#2]
hi ich habe ein prolem, uns zwar nutze ich Arduino IDE und mein esp verbindet sich nicht mit dem netzwerk.

**Comment by amonbenson** [comment]
Moin. Gibt der ESP irgentwelche Meldungen über den Serial Monitor aus? Hast du das SPIFFS Dateisystem zuerst installiert? sonst bootet der ESP nicht. Ansonsten probier mal eines von den WiFi Beispielen aus der Arduino IDE zu starten. Ist leider schon etwas her, dass ich den Code geschrieben hab; kann sein, dass da der ein oder andere Bug drin ist.

**Comment by skadzynski** [comment]
12:36:16.060 -> ⸮⸮⸮90!1%!!1%!!1%!
mehr kommt nicht über den monitor
